input1=input("Team Sheet for Euro 2020")
if input1== ("Austria"):
    print("Formation: 3511")
    print("GK: Bachmann")
    print("CB: Dragovic")
    print("CB: Alaba (C)")
    print("CB: Hinteregger")
    print("RM: Lainer")
    print("CM: Laimer")
    print("CM: Baumgartner")
    print("CM: Schlager")
    print("LM: Ulmer")
    print("CAM: Sabitzer")
    print("ST: Kalajdzic")
elif input1== ("Belgium"):
    print("Formation: 343")
    print("GK: Courtois")
    print("CB: Alderweireld")
    print("CB: Boyata")
    print("CB: Vertonghen (C)")
    print("RM: Castagne")
    print("CM: Tielemans")
    print("LM: Hazard")
    print("RW: Mertens")
    print("ST: Lukaku")
    print("LW: Cararasco")
elif input1== ("Croatia"):
    print("Formation: 4141")
    print("GK: Livakovic")
    print("RB: Vrsaljiko")
    print("CB: Vida")
    print("CB: Calera-Car")
    print("LB: Gvardiol")
    print("CDM: Brozovic")
    print("RM: Krmaric")
    print("CM: Modric (C)")
    print("CM: Kovacic")
    print("LM: Perisic")
    print("ST: Rebic")
elif input1== ("Czech Republic"):
    print("Formation: 4231")
    print("GK: Vaclik")
    print("RB: Coufal")
    print("CB: Celustka")
    print("CB: Kalas")
    print("LB: Boril")
    print("CM: Kral")
    print("CM: Soucek")
    print("RW: Masopust")
    print("CAM: Darida (C)")
    print("LW: Jankto")
    print("ST: Schick")
elif input1== ("Denmark"):
    print("Formation: 433")
    print("GK: Schmeichel")
    print("RB: Wass")
    print("CB: Kjaer (C)")
    print("CB: Christensen")
    print("LB: Maehle")
    print("CM: Eriksen")
    print("CDM: Helbjerg")
    print("CM: Delaney")
    print("RW: Poulsen")
    print("ST: Wind")
    print("LW: Braithwaite")
elif input1== ("England"):
    print("Formation: 4231")
    print("GK: Pickford")
    print("RB: Walker")
    print("CB: Stones")
    print("CB: Mings")
    print("LB: Trippier")
    print("CM: Phillips")
    print("CM: Rice")
    print("RW: Sterling")
    print("CAM: Mount")
    print("LW: Foden")
    print("ST: Kane (C)")
elif input1== ("Finland"):
    print("Formation: 352")
    print("GK: Hradecky")
    print("CB: Toivio")
    print("CB: Arajuurl")
    print("CB: O'Shaughnessy")
    print("RM: Raitala")
    print("CM: Lod")
    print("CM: Sparv (C)")
    print("CM: Kamara")
    print("LM: Uronen")
    print("ST: Pohjanpalo")
    print("ST: Pukki")
elif input1== ("France"):
    print("Formation: 4312")
    print("GK: Lloris (C)")
    print("RB: Pavard")
    print("CB: Varane")
    print("CB: Kipembe")
    print("LB: Hernandez")
    print("CM: Rabiot")
    print("CM: Kante")
    print("CM: Pogba")
    print("CAM: Griezmann")
    print("ST: Benzema")
    print("ST: Mbappe")
elif input1== ("Germany"):
    print("Formation: 3421")
    print("GK: Neuer (C)")
    print("CB: Ginter")
    print("CB: Hummels")
    print("CB: Rudiger")
    print("RM: Kimmich")
    print("CM: Gundogan")
    print("CM: Kroos")
    print("LM: Gosens")
    print("CAM: Muller")
    print("CAM: Havertz")
    print("ST: Gnabry")
elif input1== ("Hungary"):
    print("Formation: 352")
    print("GK: Gulacsi")
    print("CB: Botka")
    print("CB: Orban")
    print("CB: Szalai")
    print("RM: Lovrencsics")
    print("CM: Kleinheisler")
    print("CM: Nagy")
    print("CM: Schafer")
    print("LM: Fiola")
    print("ST: Szalai (C)")
    print("ST: Sallai")
elif input1== ("Italy"):
    print("Formation: 433")
    print("GK: Donnarumma")
    print("RB: Florenzi")
    print("CB: Bonnuci")
    print("CB: Chiellini (C)")
    print("LB: Spinazzola")
    print("CM: Barella")
    print("CM: Jorginho")
    print("CM: Locatelli")
    print("RW: Beradi")
    print("ST: Immobile")
    print("LW: Insigne")
elif input1== ("Netherlands"):
    print("Formation: 352")
    print("GK: Stekeenburg")
    print("CB: Timber")
    print("CB: De Vrij")
    print("CB: Blind")
    print("RM: Dumfries")
    print("CM: De Roon")
    print("CM: Wijnaldum (C)")
    print("CM: De Jong")
    print("LM: Van Anholt")
    print("ST: Weghorts")
    print("ST: Depay")
elif input1== ("North Macedonia"):
    print("Formation: 532")
    print("GK: Dimitrievski")
    print("RB: Nikolov")
    print("CB: Ristovski")
    print("CB: Velkovski")
    print("CB: Musliu")
    print("LB: Alioski")
    print("CM: Bardhi")
    print("CM: Ademi")
    print("LM: Elmas")
    print("ST: Pandev (C)")
    print("ST: Trajkovski")
elif input1== ("Poland"):
    print("Formation: 433")
    print("GK: Szczesny")
    print("RB: Bereszynski")
    print("CB: Glik")
    print("CB: Bednarek")
    print("LB: Rybus")
    print("CM: Linetty")
    print("CM: Krychowiak")
    print("CM: Klich")
    print("RW: Jozwiak")
    print("ST: Lewandowski (C)")
    print("LW: Zielinski")
elif input1== ("Portugal"):
    print("Formation: 4231")
    print("GK: Patricio")
    print("RB: Semedi")
    print("CB: Pepe")
    print("CB: Dias")
    print("LB: Guerrerio")
    print("CM: Pereira")
    print("CM: Carvalho")
    print("RW: Silva")
    print("CAM: Fernandes")
    print("LW: Jota")
    print("ST: Ronaldo (C)")
elif input1== ("Russia"):
    print("Formation: 4231")
    print("GK: Shunin")
    print("RB: Fernandes")
    print("CB: Semenov")
    print("CB: Dzhikiya")
    print("LB: Zhirkov")
    print("CM: Ozodoev")
    print("CM: Barinov")
    print("RW: Zobnin")
    print("CAM: Golovin")
    print("LW: Kuzyaev")
    print("ST: Dzyuba (C)")
elif input1== ("Scotland"):
    print("Formation: 3412")
    print("GK: Marshall")
    print("CB: Hendry")
    print("CB: Hanley")
    print("CB: Cooper")
    print("RM: O'Donnell")
    print("CM: McTominay")
    print("CM: Armstrong")
    print("LM: Robertson (C)")
    print("CAM: McGinn")
    print("ST: Dykes")
    print("ST: Christie")
elif input1== ("Slovakia"):
    print("Formation: 442")
    print("GK: Dubravka")
    print("RB: Pekarik")
    print("CB: Satka")
    print("CB: Skriniar")
    print("LB: Hubocan")
    print("RM: Haraslin")
    print("CM: Kucka")
    print("CM: Hromada")
    print("LM: Mak")
    print("ST: Duda")
    print("ST: Hamsik (C)")
elif input1== ("Spain"):
    print("Formation: 433")
    print("GK: Simon")
    print("RB: Llorente")
    print("CB: Laporte")
    print("CB: Torres")
    print("LB: Alba (C)")
    print("CM: Koke")
    print("CM: Rodri")
    print("CM: Pedri")
    print("RW: Torres")
    print("ST: Morata")
    print("LW: Olmo")
elif input1== ("Sweden"):
    print("Formation: 442")
    print("GK: Olsen")
    print("RB: Lustig")
    print("CB: Lindelof")
    print("CB: Danielson")
    print("LB: Augustinsson")
    print("RM: Larsson (C)")
    print("CM: Ekdal")
    print("CM: Olsson")
    print("LM: Forsberg")
    print("ST: Isak")
    print("ST: Berg")
elif input1== ("Switzerland"):
    print("Formation: 3412")
    print("GK: Sommer")
    print("CB: Elvedi")
    print("CB: Schar")
    print("CB: Akanji")
    print("RM: Mbabu")
    print("CM: Xhaka (C)")
    print("CM: Freuler")
    print("LM: Rodriguez")
    print("CAM: Shaqiri")
    print("ST: Embolo")
    print("ST: Seferovic")
elif input1== ("Turkey"):
    print("Formation: 4141")
    print("GK: Cakir")
    print("RB: Celik")
    print("CB: Demiral")
    print("CB: Soyuncu")
    print("LB: Meral")
    print("CDM: Okay Yokuslu")
    print("RM: Karaman")
    print("CM: Tufan")
    print("CM: Yazici")
    print("LM: Calhanoglu")
    print("ST: Yilmaz (C)")
elif input1== ("Croatia"):
    print("Formation: 41221")
    print("GK: Buschan")
    print("RB: Karavaev")
    print("CB: Zabarnyi")
    print("CB: Matviyenki")
    print("LB: Mykolenkil")
    print("CDM: Zinchenko")
    print("CM: Sydorchuk")
    print("CM: Malinovsky")
    print("CAM: Yarmolenko (C)")
    print("CAM: Zubkov")
    print("ST: Yaremchuk")
elif input1== ("Wales"):
    print("Formation: 433")
    print("GK: Ward")
    print("RB: Roberts")
    print("CB: Mepham")
    print("CB: Chiellini (Rodon")
    print("LB: Davies")
    print("CM: Morrell")
    print("CM: Allen")
    print("CM: Ramsey")
    print("RW: Bale (C)i")
    print("ST: Moore")
    print("LW: James")
